import '../../imports/app_imports/app_imports.dart';

const String departmentCollection = 'department';
const String subjectsCollection = 'subjects';
const String subjectsTermCollection = 'subjectsTerm';
const String sectionCollection = 'section';
const String userTypeCollection = 'userType';
const String usersCollection= 'users' ;
const String categoryCollection= 'category' ;
const String fileCollection= 'file' ;
const String subCategoryCollection= 'subCategory' ;
const String academicYearsCollection= 'academicYears' ;
const String academicTermsCollection= 'academicTerms' ;
const String coordinatorCollection= 'coordinator' ;
const String subjectCoordinatorCollection= 'subjectCoordinator' ;
const String userTypeHeadDepartment= 'Head Department' ;
const String userTypeUser= 'User' ;
const String userTypeAdmin= 'Admin' ;
const String subjectModel= 'Subjects' ;
const DateTime constDateTime = ConstDateTime(1,1,1,1,1,1,0,1);