// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG5920DVjuNVTFv7BA2qZILrvbUtxZYo4',
    appId: '1:1007195919837:web:b20442c4d845d546ced234',
    messagingSenderId: '1007195919837',
    projectId: 'archive-app-12ad9',
    authDomain: 'archive-app-12ad9.firebaseapp.com',
    storageBucket: 'archive-app-12ad9.appspot.com',
    measurementId: 'G-C23K73PLS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUw65SDEYixztaxFWaLRI9G4wDOcEAK8',
    appId: '1:1007195919837:android:198d4a2032d7c784ced234',
    messagingSenderId: '1007195919837',
    projectId: 'archive-app-12ad9',
    storageBucket: 'archive-app-12ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtoJmPn5rlIAndqBnk9zl7sTHuQge4Og',
    appId: '1:1007195919837:ios:97f81c0f916fb294ced234',
    messagingSenderId: '1007195919837',
    projectId: 'archive-app-12ad9',
    storageBucket: 'archive-app-12ad9.appspot.com',
    iosBundleId: 'com.example.archiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG5920DVjuNVTFv7BA2qZILrvbUtxZYo4',
    appId: '1:1007195919837:web:b1524e54c65148eaced234',
    messagingSenderId: '1007195919837',
    projectId: 'archive-app-12ad9',
    authDomain: 'archive-app-12ad9.firebaseapp.com',
    storageBucket: 'archive-app-12ad9.appspot.com',
    measurementId: 'G-HDK30TRSQJ',
  );
}
